In [1]:
#imports
import matplotlib.pyplot as plt
from plotly.offline import iplot
import plotly.graph_objects as go
import plotly.offline as pyo
from plotly.subplots import make_subplots
import plotly.express as px
import plotly.io as pio
import chart_studio
import chart_studio.plotly as py
import pandas as pd
import numpy as np
from pathlib import Path

Bad key savefig.frameon in file C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 421 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.4.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 472 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.4.3/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 473 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.4.3/matplotlibrc.template
or from the matplotlib source distribution
In C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\keith\anaconda3\envs\pyvizenv\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [2]:
# CSV file, Create DataFrames
file_path2 = Path("Resources/Temp_Anomaly.csv")
df_temp_metro = pd.read_csv(file_path2)
df_temp_metro.head()

,Domain Code,Domain,Area Code (FAO),Area,Element Code,Element,Months Code,Months,Year Code,Year,Unit,Value,Flag,Flag Description
0,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1991,1991,°C,-0.133,Fc,Calculated data
1,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1992,1992,°C,-0.297,Fc,Calculated data
2,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1993,1993,°C,0.223,Fc,Calculated data
3,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1994,1994,°C,0.459,Fc,Calculated data
4,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1995,1995,°C,0.401,Fc,Calculated data

In [3]:
#Cleaning Data
df_temp_metro.set_index(df_temp_metro['Year'], inplace=True)
df_temp_metro=df_temp_metro.rename(columns={'Value':'pos_temp'})
df_temp_metro.head()

,Domain Code,Domain,Area Code (FAO),Area,Element Code,Element,Months Code,Months,Year Code,Year,Unit,pos_temp,Flag,Flag Description
Year,,,,,,,,,,,,,,
1991,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1991,1991,°C,-0.133,Fc,Calculated data
1992,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1992,1992,°C,-0.297,Fc,Calculated data
1993,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1993,1993,°C,0.223,Fc,Calculated data
1994,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1994,1994,°C,0.459,Fc,Calculated data
1995,ET,Temperature change,2,Afghanistan,7271,Temperature change,7020,Meteorological year,1995,1995,°C,0.401,Fc,Calculated data

In [4]:
#choropleth map

fig=px.choropleth(df_temp_metro,
                  locations='Area',
                  locationmode='country names',
                  animation_frame='Year',
                  animation_group='Area',
                  color='pos_temp',
                  color_continuous_scale= 'reds',
                  hover_name='Area', 
                  title = 'Global Temperature Anomaly')
fig.show()

NameError: name 'px' is not defined

The Intergovernmental Panel on Climate Control (IPCC) report, indecates that the earth temperature is unfortunately racing towards 1.5 degrees celcius above pre-industrial levels. Pre-industrial levels are the recorded temperatures between 1850 and 1900 which is the period of time before the start of the industrial revolution in the early 1900s. 
As the change in temperature increases towards 1.5 degrees, it is estimated that the number of natural disasters being faced will double in frequency. Furthermore, if we are to achieve 2 degrees celcius above pre-industrial levels we would expect natural disasters to quadruple in frequency, with noticeable mentions in severity. Droughts are prolonged, huricanes, cyclones are more severe and the number of wild fires will increase exponential as we have been experiencing. 

The effects of Climate Change on the earth is a story which began in the Carboniferous Period, 360 millions years ago when most of the earth's land was forested. When these trees died, the carbon that they stored was trapped underground for millions of years until it was brought back up and put back into the atmosphere at an unnatural rate.